// Generated by ReScript, PLEASE EDIT WITH CARE


var Scroll = {};

function scrollTo(id, behaviorOpt) {
  var behavior = behaviorOpt !== undefined ? behaviorOpt : "smooth";
  var element = document.getElementById(id);
  if (element !== undefined) {
    return element.scrollIntoView({
                behavior: behavior
              });
  }
  
}

export {
  Scroll ,
  scrollTo ,
}
/* No side effect */
