// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SupabaseJs from "@supabase/supabase-js";

function progressId(id) {
  return "progress-" + id;
}

function make() {
  return {
          getItem: (function (prim) {
              return localStorage.getItem(prim);
            }),
          setItem: (function (prim0, prim1) {
              localStorage.setItem(prim0, prim1);
            }),
          getAllKeys: (function (prim) {
              return localStorage.getAllKeys();
            })
        };
}

var Local = {
  progressId: progressId,
  make: make
};

function make$1(url, anonKey) {
  return SupabaseJs.createClient(url, anonKey);
}

var Supabase = {
  make: make$1
};

export {
  Local ,
  Supabase ,
}
/* @supabase/supabase-js Not a pure module */
