// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";
import * as Stack from "../domain/api/entity/Stack.mjs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as CardProgress from "../domain/api/entity/CardProgress.mjs";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as SupabaseJs from "@supabase/supabase-js";

async function fetchData(path) {
  try {
    var response = await fetch(path);
    return await response.text();
  }
  catch (raw_error){
    var error = Caml_js_exceptions.internalToOCamlException(raw_error);
    if (error.RE_EXN_ID === Js_exn.$$Error) {
      console.log("Error fetching data: ", error._1);
    } else {
      console.log("Unknown error");
    }
    return ;
  }
}

var Browser = {
  fetchData: fetchData
};

var Supabase = {};

function make(url, anonKey) {
  var client = SupabaseJs.createClient(url, anonKey);
  var settingsCache = {};
  return {
          stack: {
            toc: (async function (path) {
                var fullPath = path === "/" ? "/stacks-toc.json" : path + "/stacks-toc.json";
                var body = await fetchData(fullPath);
                if (body === undefined) {
                  return [];
                }
                try {
                  var json = JSON.parse(body);
                  return S.parseOrThrow(json, Stack.tocSchema);
                }
                catch (raw_e){
                  var e = Caml_js_exceptions.internalToOCamlException(raw_e);
                  if (e.RE_EXN_ID === Js_exn.$$Error) {
                    console.log("Error parsing TOC:", e._1.message);
                    return [];
                  } else {
                    console.log("Error parsing TOC JSON");
                    return [];
                  }
                }
              }),
            get: (async function (id) {
                var body = await fetchData("/stacks/" + id + ".json");
                if (body === undefined) {
                  return ;
                }
                try {
                  var json = JSON.parse(body);
                  return S.parseOrThrow(json, Stack.stackSchema);
                }
                catch (raw_e){
                  var e = Caml_js_exceptions.internalToOCamlException(raw_e);
                  if (e.RE_EXN_ID === Js_exn.$$Error) {
                    console.log("Error parsing stack:", e._1.message);
                  } else {
                    console.log("Error parsing stack JSON");
                  }
                  return ;
                }
              })
          },
          progress: {
            get: (async function (id) {
                var table = client.from("progress");
                var query = table.select("*").eq("stack_id", id);
                var response = await query.maybeSingle();
                var row = response.data;
                if (row === undefined) {
                  return ;
                }
                try {
                  var cards = S.parseOrThrow(row.cards, S.dict(CardProgress.progressSchema));
                  return {
                          id: row.stack_id,
                          active: row.active,
                          cards: cards
                        };
                }
                catch (raw_e){
                  var e = Caml_js_exceptions.internalToOCamlException(raw_e);
                  if (e.RE_EXN_ID === Js_exn.$$Error) {
                    console.log("Error parsing progress cards from DB:", e._1.message);
                    return ;
                  } else {
                    return ;
                  }
                }
              }),
            save: (async function (progress) {
                try {
                  var cardsJsonUnknown = S.reverseConvertOrThrow(progress.cards, S.dict(CardProgress.progressSchema));
                  var row_stack_id = progress.id;
                  var row_active = progress.active;
                  var row = {
                    stack_id: row_stack_id,
                    active: row_active,
                    cards: cardsJsonUnknown
                  };
                  var table = client.from("progress");
                  var query = table.upsert(row);
                  var response = await query.maybeSingle();
                  var error = response.error;
                  if (error !== undefined) {
                    console.log("[Supabase.saveProgress] Error saving progress: ", error.message);
                    return ;
                  } else {
                    return ;
                  }
                }
                catch (raw_e){
                  var e = Caml_js_exceptions.internalToOCamlException(raw_e);
                  if (e.RE_EXN_ID === Js_exn.$$Error) {
                    console.log("[Supabase.saveProgress] Error serializing cards: ", e._1.message);
                    return ;
                  } else {
                    return ;
                  }
                }
              })
          },
          settings: {
            get: (function (key) {
                var value = settingsCache[key];
                if (value !== undefined) {
                  return value;
                } else {
                  return null;
                }
              }),
            save: (function (key, value) {
                settingsCache[key] = value;
              })
          }
        };
}

export {
  Browser ,
  Supabase ,
  make ,
}
/* S Not a pure module */
