// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";
import * as Stack from "../domain/api/entity/Stack.mjs";
import * as SupabaseJs from "@supabase/supabase-js";

var Client = {};

var Auth = {};

var Query = {};

var $$Navigator = {};

var client = SupabaseJs.createClient("https://ymasvqhkmgrhwfpvojgk.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltYXN2cWhrbWdyaHdmcHZvamdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxOTIwMDQsImV4cCI6MjA3Nzc2ODAwNH0.dFmQKiq7ce8uZ_iGP03OTxwWQ6eIRW9lT3xpwiMBDHU");

function getClient() {
  return client;
}

async function getSession(client) {
  var auth = client.auth;
  var response = await auth.getSession();
  var data = response.data;
  if (data !== undefined) {
    return data.session;
  }
  
}

async function signIn(client, email, password) {
  var auth = client.auth;
  var response = await auth.signInWithPassword({
        email: email,
        password: password
      });
  var _error = response.error;
  if (_error !== undefined) {
    return ;
  }
  var data = response.data;
  if (data !== undefined) {
    return data.session;
  }
  
}

async function signInResult(client, email, password) {
  var auth = client.auth;
  var response = await auth.signInWithPassword({
        email: email,
        password: password
      });
  var hasError = (response.error !== null && response.error !== undefined);
  if (hasError) {
    var errorMsg = ((response.error && response.error !== null && response.error.message && response.error.message !== null && response.error.message !== "null") 
        ? response.error.message 
        : (response.error && response.error !== null && response.error.msg && response.error.msg !== null && response.error.msg !== "null")
          ? response.error.msg
          : "La connexion a échoué. Veuillez vérifier vos identifiants.");
    return {
            TAG: "Error",
            _0: errorMsg
          };
  }
  var data = response.data;
  if (data === undefined) {
    return {
            TAG: "Error",
            _0: "La connexion a échoué. Veuillez vérifier vos identifiants."
          };
  }
  var session = data.session;
  if (session !== undefined) {
    return {
            TAG: "Success",
            _0: session
          };
  } else {
    return {
            TAG: "Error",
            _0: "La connexion a échoué. Veuillez vérifier vos identifiants."
          };
  }
}

async function signUp(client, email, password) {
  var auth = client.auth;
  var response = await auth.signUp({
        email: email,
        password: password
      });
  var _error = response.error;
  if (_error !== undefined) {
    return ;
  }
  var data = response.data;
  if (data !== undefined) {
    return data.session;
  }
  
}

async function signUpResult(client, email, password) {
  var auth = client.auth;
  var response = await auth.signUp({
        email: email,
        password: password
      });
  var hasError = (response.error !== null && response.error !== undefined);
  if (hasError) {
    var errorMsg = ((response.error && response.error !== null && response.error.message && response.error.message !== null && response.error.message !== "null") 
        ? response.error.message 
        : (response.error && response.error !== null && response.error.msg && response.error.msg !== null && response.error.msg !== "null")
          ? response.error.msg
          : "L'inscription a échoué. Veuillez réessayer.");
    return {
            TAG: "Error",
            _0: errorMsg
          };
  }
  var data = response.data;
  if (data === undefined) {
    return {
            TAG: "Error",
            _0: "L'inscription a échoué. Veuillez réessayer."
          };
  }
  var sessionExists = (data.session !== null && data.session !== undefined);
  if (!sessionExists) {
    return "EmailConfirmationRequired";
  }
  var session = data.session;
  if (session !== undefined) {
    return {
            TAG: "Success",
            _0: session
          };
  } else {
    return "EmailConfirmationRequired";
  }
}

async function signUpWithError(client, email, password) {
  var result = await signUpResult(client, email, password);
  if (typeof result !== "object") {
    return [
            undefined,
            "Veuillez vérifier votre email pour confirmer votre compte. Un email de confirmation a été envoyé."
          ];
  } else if (result.TAG === "Success") {
    return [
            result._0,
            undefined
          ];
  } else {
    return [
            undefined,
            result._0
          ];
  }
}

async function signOut(client) {
  var auth = client.auth;
  var response = await auth.signOut();
  var match = response.error;
  return match === undefined;
}

function onAuthStateChange(client, callback) {
  var auth = client.auth;
  var supabaseCallback = function ($$event, sessionOpt) {
    var mappedEvent;
    switch ($$event) {
      case "INITIAL_SESSION" :
          if (sessionOpt !== undefined) {
            console.log("[Supabase] INITIAL_SESSION event received with session, userId=" + sessionOpt.user.id);
            mappedEvent = {
              TAG: "SignedIn",
              _0: sessionOpt
            };
          } else {
            console.log("[Supabase] INITIAL_SESSION event received but no session");
            mappedEvent = "SignedOut";
          }
          break;
      case "SIGNED_IN" :
          if (sessionOpt !== undefined) {
            console.log("[Supabase] SIGNED_IN event received, session.user.id=" + sessionOpt.user.id);
            mappedEvent = {
              TAG: "SignedIn",
              _0: sessionOpt
            };
          } else {
            console.log("[Supabase] SIGNED_IN event received but session is null");
            mappedEvent = "SignedOut";
          }
          break;
      case "SIGNED_OUT" :
          console.log("[Supabase] SIGNED_OUT event received");
          mappedEvent = "SignedOut";
          break;
      case "TOKEN_REFRESHED" :
          mappedEvent = sessionOpt !== undefined ? ({
                TAG: "TokenRefreshed",
                _0: sessionOpt
              }) : "SignedOut";
          break;
      case "USER_UPDATED" :
          mappedEvent = sessionOpt !== undefined ? ({
                TAG: "UserUpdated",
                _0: sessionOpt
              }) : "SignedOut";
          break;
      default:
        console.log("[Supabase] Unknown auth event: " + $$event);
        mappedEvent = "SignedOut";
    }
    callback(mappedEvent);
  };
  auth.onAuthStateChange(supabaseCallback);
}

async function getProgress(client, userId, stackId) {
  var table = client.from("progress");
  var select = table.select("*");
  var query = select.eq("user_id", userId);
  var eqQuery = query.eq("stack_id", stackId);
  var response = await eqQuery.maybeSingle();
  var row = response.data;
  if (row === undefined) {
    return ;
  }
  var activeStr = row.active ? "true" : "false";
  var fullProgressJson = "{\"id\":\"" + stackId + "\",\"active\":" + activeStr + ",\"cards\":" + row.cards + "}";
  try {
    return S.parseJsonStringOrThrow(fullProgressJson, Stack.progressSchema);
  }
  catch (exn){
    return ;
  }
}

async function getAllProgress(client, userId) {
  var table = client.from("progress");
  var select = table.select("*");
  var query = select.eq("user_id", userId);
  await query.maybeSingle();
  return [];
}

async function saveProgress(client, userId, progress) {
  S.reverseConvertOrThrow(progress, Stack.progressSchema);
  var cardsJson = (JSON.stringify(progressJson.cards));
  var row = {
    user_id: userId,
    stack_id: progress.id,
    active: progress.active,
    cards: cardsJson
  };
  console.log("[Supabase.saveProgress] Saving progress for stack " + progress.id);
  var table = client.from("progress");
  var upsert = table.upsert(row);
  var response = await upsert.maybeSingle();
  var error = response.error;
  if (error !== undefined) {
    console.log("[Supabase.saveProgress] Error saving progress for " + progress.id + ": " + error.message);
    return false;
  } else {
    console.log("[Supabase.saveProgress] Successfully saved progress for " + progress.id);
    return true;
  }
}

function online() {
  return navigator.onLine;
}

function onOnline(callback) {
  window.addEventListener("online", callback);
}

function onOffline(callback) {
  window.addEventListener("offline", callback);
}

function removeOnOnline(callback) {
  window.removeEventListener("online", callback);
}

function removeOnOffline(callback) {
  window.removeEventListener("offline", callback);
}

export {
  Client ,
  Auth ,
  Query ,
  $$Navigator ,
  client ,
  getClient ,
  getSession ,
  signIn ,
  signInResult ,
  signUp ,
  signUpResult ,
  signUpWithError ,
  signOut ,
  onAuthStateChange ,
  getProgress ,
  getAllProgress ,
  saveProgress ,
  online ,
  onOnline ,
  onOffline ,
  removeOnOnline ,
  removeOnOffline ,
}
/* client Not a pure module */
