// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";

var Fs = {};

var Path = {};

var Process = {};

function readdirSync(path) {
  return Nodefs.readdirSync(path, {
              encoding: "utf8",
              withFileTypes: true
            });
}

function make() {
  return {
          fs: {
            existsSync: (function (prim) {
                return Nodefs.existsSync(prim);
              }),
            readFileSync: (function (prim0, prim1) {
                return Nodefs.readFileSync(prim0, prim1);
              }),
            readdirSync: readdirSync,
            writeFileSync: (function (prim0, prim1, prim2) {
                Nodefs.writeFileSync(prim0, prim1, prim2);
              }),
            mkdirSync: (function (prim) {
                Nodefs.mkdirSync(prim);
              })
          },
          path: {
            join: (function (prim0, prim1) {
                return Nodepath.join(prim0, prim1);
              })
          },
          process: {
            cwd: (function (prim) {
                return process.cwd();
              })
          }
        };
}

export {
  Fs ,
  Path ,
  Process ,
  readdirSync ,
  make ,
}
/* node:fs Not a pure module */
