// Generated by ReScript, PLEASE EDIT WITH CARE


function partition(list, predicate) {
  var map = new Map();
  list.forEach(function (item) {
        var key = predicate(item);
        var match = map.get(key);
        var list = match !== undefined ? match.list : [];
        list.push(item);
        map.set(key, {
              key: key,
              list: list
            });
      });
  return Array.from(map.values());
}

export {
  partition ,
}
/* No side effect */
