// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";
import * as Core__Int from "@rescript/core/src/Core__Int.mjs";

var hard = 1 * 3600 * 24;

var good = 3 * 3600 * 24;

var easy = 6 * 3600 * 24;

function recallTime(timestamp, s) {
  if (typeof s === "object") {
    return timestamp + easy * Math.pow(s._0, 2);
  }
  switch (s) {
    case "again" :
        return timestamp + 0;
    case "hard" :
        return timestamp + hard;
    case "good" :
        return timestamp + good;
    
  }
}

function easyState(prevState) {
  if (typeof prevState !== "object") {
    return {
            kind: "easy",
            _0: 1
          };
  } else {
    return {
            kind: "easy",
            _0: prevState._0 + 1 | 0
          };
  }
}

function ofString(s) {
  switch (s) {
    case "Again" :
        return "again";
    case "Good" :
        return "good";
    case "Hard" :
        return "hard";
    default:
      if (s.startsWith("Easy:")) {
        var i = Core__Int.fromString(s.slice(5), undefined);
        if (i !== undefined) {
          return {
                  kind: "easy",
                  _0: i
                };
        } else {
          return {
                  kind: "easy",
                  _0: 1
                };
        }
      }
      throw {
            RE_EXN_ID: "Invalid_argument",
            _1: "'" + s + "' is not a valid state",
            Error: new Error()
          };
  }
}

var easySchema = S.schema(function (s) {
      return {
              kind: "easy",
              _0: s.m(S.$$int)
            };
    });

var progressSchema = S.object(function (s) {
      return {
              timestamp: s.f("timestamp", S.$$float),
              recall: s.f("recall", S.$$float),
              state: s.f("state", S.union([
                        S.literal("again"),
                        S.literal("hard"),
                        S.literal("good"),
                        easySchema
                      ]))
            };
    });

var again = 0;

export {
  again ,
  hard ,
  good ,
  easy ,
  recallTime ,
  easyState ,
  ofString ,
  easySchema ,
  progressSchema ,
}
/* easySchema Not a pure module */
