// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.mjs";

var hard = 1 * 3600 * 24;

var good = 3 * 3600 * 24;

var easy = 6 * 3600 * 24;

function recallTime(timestamp, s) {
  if (typeof s === "object") {
    return timestamp + easy * Math.pow(s._0, 2);
  }
  switch (s) {
    case "Again" :
        return timestamp + 0;
    case "Hard" :
        return timestamp + hard;
    case "Good" :
        return timestamp + good;
    
  }
}

function easyState(prevState) {
  if (typeof prevState !== "object") {
    return {
            TAG: "Easy",
            _0: 1
          };
  } else {
    return {
            TAG: "Easy",
            _0: prevState._0 + 1 | 0
          };
  }
}

function ofString(s) {
  switch (s) {
    case "Again" :
        return "Again";
    case "Good" :
        return "Good";
    case "Hard" :
        return "Hard";
    default:
      if (s.startsWith("Easy:")) {
        var i = Core__Int.fromString(s.slice(5), undefined);
        if (i !== undefined) {
          return {
                  TAG: "Easy",
                  _0: i
                };
        } else {
          return {
                  TAG: "Easy",
                  _0: 1
                };
        }
      }
      throw {
            RE_EXN_ID: "Invalid_argument",
            _1: "'" + s + "' is not a valid state",
            Error: new Error()
          };
  }
}

var again = 0;

export {
  again ,
  hard ,
  good ,
  easy ,
  recallTime ,
  easyState ,
  ofString ,
}
/* No side effect */
