// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";

var qoptionSchema = S.object(function (s) {
      return {
              id: s.f("id", S.string),
              content: s.f("content", S.string),
              correct: s.f("correct", S.bool)
            };
    });

var cardSchema = S.object(function (s) {
      return {
              id: s.f("id", S.string),
              stackId: s.f("stackId", S.string),
              content: s.f("content", S.string),
              solution: s.f("solution", S.string),
              options: s.f("options", S.array(qoptionSchema))
            };
    });

export {
  qoptionSchema ,
  cardSchema ,
}
/* qoptionSchema Not a pure module */
