// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";
import * as Card from "./Card.mjs";
import * as CardProgress from "./CardProgress.mjs";

var stackTypeSchema = S.union([
      S.literal("cards"),
      S.literal("quiz")
    ]);

var levelSchema = S.union([
      S.literal("regular"),
      S.literal("pro")
    ]);

var infoSchema = S.object(function (s) {
      return {
              id: s.f("id", S.string),
              title: s.f("title", S.string),
              kind: s.f("type", stackTypeSchema),
              level: s.f("level", levelSchema),
              chapter: s.f("chapter", S.string),
              course: s.f("course", S.string),
              tags: s.f("tags", S.array(S.string)),
              count: s.f("count", S.option(S.$$int))
            };
    });

var progressSchema = S.object(function (s) {
      return {
              id: s.f("id", S.string),
              active: s.f("active", S.bool),
              cards: s.f("cards", S.dict(CardProgress.progressSchema))
            };
    });

var stackSchema = S.object(function (s) {
      return {
              info: s.f("info", infoSchema),
              cards: s.f("cards", S.array(Card.cardSchema))
            };
    });

var tocSchema = S.array(infoSchema);

export {
  stackTypeSchema ,
  levelSchema ,
  infoSchema ,
  progressSchema ,
  stackSchema ,
  tocSchema ,
}
/* stackTypeSchema Not a pure module */
