// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";
import * as CardProgress from "./CardProgress.mjs";

var infoSchema = S.object(function (s) {
      return {
              id: s.f("id", S.string),
              title: s.f("title", S.string),
              kind: s.f("type", S.union([
                        S.literal("cards"),
                        S.literal("quiz")
                      ])),
              level: s.f("level", S.union([
                        S.literal("regular"),
                        S.literal("pro")
                      ])),
              chapter: s.f("chapter", S.string),
              course: s.f("course", S.string),
              tags: s.f("tags", S.array(S.string))
            };
    });

var progressSchema = S.object(function (s) {
      return {
              id: s.f("id", S.string),
              active: s.f("active", S.bool),
              cards: s.f("cards", S.dict(CardProgress.progressSchema))
            };
    });

export {
  infoSchema ,
  progressSchema ,
}
/* infoSchema Not a pure module */
