// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";
import * as Card from "./Card.mjs";
import * as CardProgress from "./CardProgress.mjs";

function stackTypeToString(stackType) {
  switch (stackType) {
    case "cards" :
        return "Cards";
    case "quiz" :
        return "Quiz";
    case "proofs" :
        return "Proofs";
    
  }
}

function stackTypeToEmoji(stackType) {
  switch (stackType) {
    case "cards" :
        return "📚";
    case "quiz" :
        return "✅";
    case "proofs" :
        return "👁️";
    
  }
}

function levelToString(level) {
  if (level === "regular") {
    return "Regular";
  } else {
    return "Pro";
  }
}

var stackTypeSchema = S.union([
      S.literal("cards"),
      S.literal("quiz"),
      S.literal("proofs")
    ]);

var levelSchema = S.union([
      S.literal("regular"),
      S.literal("pro")
    ]);

var infoSchema = S.object(function (s) {
      return {
              id: s.f("id", S.string),
              title: s.f("title", S.string),
              kind: s.f("type", stackTypeSchema),
              level: s.f("level", levelSchema),
              chapter: s.f("chapter", S.string),
              course: s.f("course", S.string),
              tags: s.f("tags", S.array(S.string)),
              count: s.f("count", S.option(S.$$int))
            };
    });

var progressSchema = S.object(function (s) {
      return {
              id: s.f("id", S.string),
              active: s.f("active", S.bool),
              cards: s.f("cards", S.dict(CardProgress.progressSchema))
            };
    });

var stackSchema = S.object(function (s) {
      return {
              info: s.f("info", infoSchema),
              cards: s.f("cards", S.array(Card.cardSchema))
            };
    });

var tocSchema = S.array(infoSchema);

export {
  stackTypeToString ,
  stackTypeToEmoji ,
  levelToString ,
  stackTypeSchema ,
  levelSchema ,
  infoSchema ,
  progressSchema ,
  stackSchema ,
  tocSchema ,
}
/* stackTypeSchema Not a pure module */
