// Generated by ReScript, PLEASE EDIT WITH CARE


function box(random) {
  var u1 = random();
  var u2 = random();
  var r = Math.sqrt(-2.0 * Math.log(u1));
  var theta = 2.0 * Math.PI * u2;
  return {
          z0: r * Math.cos(theta),
          z1: r * Math.sin(theta)
        };
}

var BoxMuller = {
  box: box
};

function band(_a, _b) {
  return (_a & _b);
}

function xor(_a, _b) {
  return (_a ^ _b);
}

function floatToSeed(seed) {
    var buffer = new ArrayBuffer(8);
    var floatView = new Float64Array(buffer);
    var intView = new Uint32Array(buffer);
    floatView[0] = seed;
    return intView[0] ^ intView[1];
  }
;

function floatToSeed$1(prim) {
  return floatToSeed(prim);
}

var Bitwise = {
  band: band,
  xor: xor,
  floatToSeed: floatToSeed$1
};

function withSeed(seed) {
  var state = {
    contents: floatToSeed(seed)
  };
  return function () {
    var multiplied = Math.imul(state.contents, 1664525);
    var added = multiplied + 1013904223 | 0;
    var next = band(added, 2147483647);
    state.contents = next;
    return next / 2147483648.0;
  };
}

function make(random) {
  return function (mu, sigma) {
    var leftover;
    var z = leftover;
    if (z !== undefined) {
      leftover = undefined;
      return mu + sigma * z;
    }
    var match = box(random);
    leftover = match.z1;
    return mu + sigma * match.z0;
  };
}

function ofSeed(seed, mu, sigma) {
  var match = box(withSeed(seed));
  return mu + sigma * match.z0;
}

var Gaussian = {
  make: make,
  ofSeed: ofSeed
};

function noop(mu, _sigma) {
  return mu;
}

export {
  BoxMuller ,
  Bitwise ,
  withSeed ,
  Gaussian ,
  noop ,
}
/*  Not a pure module */
