// Generated by ReScript, PLEASE EDIT WITH CARE


var Ui = {};

function make(param) {
  var view = {
    TAG: "Front",
    _0: {
      content: "",
      options: undefined,
      turn: (function () {
          
        })
    }
  };
  return {
          view: view
        };
}

function sort(cards) {
  return cards.toSorted(function (param, param$1) {
              var aProgress = param[1].timestamp;
              var bProgress = param$1[1].timestamp;
              if (aProgress < bProgress) {
                return -1.0;
              } else {
                return 1.0;
              }
            });
}

export {
  Ui ,
  make ,
  sort ,
}
/* No side effect */
