// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Recall from "./Recall.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function start(repo) {
  return function (param) {
    var stacks = param.stacks;
    return async function (setRecall) {
      var stacks$1 = Core__Array.keepSome(await Promise.all(stacks.map(async function (param) {
                    var prog = param.prog;
                    var info = param.info;
                    if (typeof prog !== "object") {
                      return ;
                    }
                    var prog$1 = prog._0;
                    if (!prog$1.active) {
                      return ;
                    }
                    var stack = await repo.stack.get(info.id);
                    if (stack !== undefined) {
                      return {
                              stack: stack,
                              prog: prog$1
                            };
                    } else {
                      console.log("Stack not found: ", info.id);
                      return ;
                    }
                  })));
      return setRecall(Recall.make(repo, stacks$1));
    };
  };
}

async function loadProgress(prog, set, info) {
  var p = await prog.get(info.id);
  if (p !== undefined) {
    return set({
                info: info,
                prog: {
                  TAG: "Started",
                  _0: p
                }
              });
  } else {
    return set({
                info: info,
                prog: "NotStarted"
              });
  }
}

function stacks(repo, path) {
  return async function (setList) {
    var list = (await repo.stack.toc(path)).map(function (info) {
          return {
                  info: info,
                  prog: "Loading"
                };
        });
    setList(list);
    list.forEach(function (param, i) {
          loadProgress(repo.progress, (function (extra) {
                  list[i] = extra;
                }), param.info);
        });
  };
}

function setActive(param) {
  var save = param.save;
  return function (param) {
    var stacks = param.stacks;
    return function (id, active) {
      var i = stacks.findIndex(function (v) {
            return v.info.id === id;
          });
      if (i === -1) {
        return ;
      }
      var match = stacks[i];
      if (match === undefined) {
        return ;
      }
      var p = match.prog;
      var info = match.info;
      if (typeof p !== "object") {
        if (p === "Loading") {
          return ;
        }
        var p$1 = {
          id: info.id,
          active: active,
          cards: {}
        };
        stacks[i] = {
          info: info,
          prog: {
            TAG: "Started",
            _0: p$1
          }
        };
        save(p$1);
        return ;
      } else {
        var p$2 = p._0;
        p$2.active = active;
        save(p$2);
        return ;
      }
    };
  };
}

function make(repo, path) {
  return Tilia.carve(function (param) {
              var derived = param.derived;
              return {
                      stacks: Tilia.source(stacks(repo, path), []),
                      setActive: derived(setActive(repo.progress)),
                      start: derived(start(repo))
                    };
            });
}

export {
  start ,
  loadProgress ,
  stacks ,
  setActive ,
  make ,
}
/* Tilia Not a pure module */
