// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Core__Float from "@rescript/core/src/Core__Float.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as Core__Nullable from "@rescript/core/src/Core__Nullable.mjs";

function clamp(value, min, max) {
  if (value < min) {
    return min;
  } else if (value > max) {
    return max;
  } else {
    return value;
  }
}

function make(repo) {
  var fontSize = clamp(Core__Option.getOr(Core__Float.fromString(Core__Nullable.getOr(repo.settings.get("fontSize"), (18.0).toString())), 18.0), 10.0, 32.0);
  var match = Tilia.signal(fontSize);
  var setFontSizeH = match[1];
  var fontSizeH = match[0];
  var increaseFontSize = function () {
    var newSize = clamp(fontSizeH.value + 1.0, 10.0, 32.0);
    repo.settings.save("fontSize", newSize.toString());
    setFontSizeH(newSize);
  };
  var decreaseFontSize = function () {
    var newSize = clamp(fontSizeH.value - 1.0, 10.0, 32.0);
    repo.settings.save("fontSize", newSize.toString());
    setFontSizeH(newSize);
  };
  return Tilia.carve(function (param) {
              return {
                      fontSize: Tilia.lift(fontSizeH),
                      increaseFontSize: increaseFontSize,
                      decreaseFontSize: decreaseFontSize
                    };
            });
}

export {
  clamp ,
  make ,
}
/* Tilia Not a pure module */
