// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as System from "../../service/System.mjs";
import * as StackParser from "./StackParser.mjs";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function $$default() {
  var done = {
    contents: false
  };
  return {
          name: "stack-json-generator",
          buildStart: (function () {
              if (done.contents) {
                return ;
              }
              done.contents = true;
              var system = System.make();
              var generator = StackParser.makeStacksToJson(system.fs, system.path);
              try {
                var toc = generator("src/pages", "public", "public/stacks");
                console.log("*********************************************\nStacks to JSON: " + toc.length.toString() + " stacks generated\n*******************************************************");
                return ;
              }
              catch (raw_error){
                var error = Caml_js_exceptions.internalToOCamlException(raw_error);
                if (error.RE_EXN_ID === Js_exn.$$Error) {
                  console.log("Error during stack JSON generation:");
                  console.log(error._1);
                } else {
                  console.log("Error during stack JSON generation:");
                  console.log("Unknown error");
                }
                return ;
              }
            })
        };
}

export {
  $$default as default,
}
/* System Not a pure module */
