// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";
import * as VitestBdd from "vitest-bdd";
import * as Core__Float from "@rescript/core/src/Core__Float.mjs";
import * as CardProgress from "../api/entity/CardProgress.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

VitestBdd.Given("a card evaluation", (function (param, table) {
        param.step("the recall times should match", (function () {
                VitestBdd.toRecords(table).forEach(function (record) {
                      var timestamp = Core__Option.getExn(Core__Float.fromString(Core__Option.getExn(record.day, undefined)), undefined) * 3600 * 24;
                      var state = CardProgress.ofString(Core__Option.getExn(record.state, undefined));
                      Vitest.expect(CardProgress.recallTime(timestamp, state, undefined) / 3600 / 24).toBe(Core__Option.getExn(Core__Float.fromString(Core__Option.getExn(record.recall, undefined)), undefined));
                    });
              }));
      }));

export {
  
}
/*  Not a pure module */
