// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Random from "../feature/Random.mjs";
import * as Vitest from "vitest";
import * as Core__Int from "@rescript/core/src/Core__Int.mjs";
import * as VitestBdd from "vitest-bdd";
import * as Core__Float from "@rescript/core/src/Core__Float.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

VitestBdd.Given("a random generator with seed {number}", (function (param, seed) {
        var random = Random.withSeed(seed);
        param.step("the random generator should produce the following numbers", (function (table) {
                var numbers = VitestBdd.toNumbers(table);
                numbers.forEach(function (nb) {
                      Vitest.expect(random()).toBeCloseTo(nb, 2);
                    });
              }));
      }));

VitestBdd.Given("float numbers to use as seed", (function (param, table) {
        var entries = VitestBdd.toRecords(table);
        param.step("the float numbers should match the seed", (function () {
                entries.forEach(function (entry) {
                      Vitest.expect(Random.Bitwise.floatToSeed(Core__Option.getExn(Core__Float.fromString(entry.float), undefined))).toBe(Core__Option.getExn(Core__Int.fromString(entry.seed, undefined), undefined));
                    });
              }));
      }));

export {
  
}
/*  Not a pure module */
