// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RecallToc from "../domain/feature/RecallToc.mjs";
import * as Repository from "../service/Repository.mjs";

var repo = Repository.make("/stacks");

var $$Window = {};

var app = {
  toc: RecallToc.make(repo, window.location.pathname)
};

export {
  repo ,
  $$Window ,
  app ,
}
/* repo Not a pure module */
