// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Settings from "../domain/feature/Settings.mjs";
import * as RecallToc from "../domain/feature/RecallToc.mjs";
import * as Repository from "../service/Repository.mjs";

var repo = Repository.make("/stacks");

var $$Window = {};

function make() {
  var match = Tilia.signal(undefined);
  var setRecall = match[1];
  var recall = match[0];
  return Tilia.carve(function (param) {
              return {
                      toc: RecallToc.make(repo, window.location.pathname),
                      recall: Tilia.lift(recall),
                      start: param.derived(function (param) {
                            var toc = param.toc;
                            return function () {
                              toc.start(setRecall);
                            };
                          }),
                      done: (function () {
                          setRecall(undefined);
                        }),
                      settings: Settings.make(repo)
                    };
            });
}

var app = make();

export {
  repo ,
  $$Window ,
  make ,
  app ,
}
/* repo Not a pure module */
