// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as RecallView from "./RecallView.mjs";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as RecallTocView from "./RecallTocView.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function AppView(props) {
  TiliaReact.useTilia();
  var recall = App.app.recall;
  return JsxRuntime.jsx("div", {
              children: recall !== undefined ? JsxRuntime.jsx(RecallView.make, {
                      recall: recall
                    }) : JsxRuntime.jsx(RecallTocView.make, {})
            });
}

var make = AppView;

export {
  make ,
}
/* App Not a pure module */
