// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as React from "react";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function setCSSProperty(name, value) {
  ((document.documentElement.style.setProperty(arguments[0], arguments[1])));
}

function FontSizeView(props) {
  TiliaReact.useTilia();
  var settings = App.app.settings;
  var fontSize = settings.fontSize;
  React.useEffect((function () {
          setCSSProperty("--font-size", fontSize.toString() + "px");
        }), [fontSize]);
  var atMin = fontSize <= 12.0;
  var atMax = fontSize >= 24.0;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                      children: "A",
                      "aria-label": "Decrease font size",
                      className: "font-size-control text-base hover:text-gray-900 disabled:opacity-30 disabled:cursor-not-allowed",
                      disabled: atMin,
                      onClick: (function (param) {
                          settings.decreaseFontSize();
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "A",
                      "aria-label": "Increase font size",
                      className: "font-size-control text-xl hover:text-gray-900 disabled:opacity-30 disabled:cursor-not-allowed",
                      disabled: atMax,
                      onClick: (function (param) {
                          settings.increaseFontSize();
                        })
                    })
              ],
              className: "flex items-center gap-1 text-gray-600"
            });
}

var make = FontSizeView;

export {
  setCSSProperty ,
  make ,
}
/* App Not a pure module */
