// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as Browser from "../service/Browser.mjs";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import MarkdownTsx from "./Markdown.tsx";
import * as JsxRuntime from "react/jsx-runtime";

var make = MarkdownTsx;

var Markdown = {
  make: make
};

function RecallView$Options(props) {
  var options = props.options;
  TiliaReact.useTilia();
  if (options.length === 0) {
    return JsxRuntime.jsx(JsxRuntime.Fragment, {});
  } else {
    return JsxRuntime.jsx("ul", {
                children: options.map(function (option) {
                      return JsxRuntime.jsxs("li", {
                                  children: [
                                    JsxRuntime.jsx("input", {
                                          checked: option.checked,
                                          type: "checkbox",
                                          onChange: (function (param) {
                                              
                                            })
                                        }),
                                    JsxRuntime.jsx(make, {
                                          text: option.content
                                        })
                                  ],
                                  onClick: (function (param) {
                                      option.checked = !option.checked;
                                    })
                                }, option.id);
                    }),
                className: "options"
              });
  }
}

var Options = {
  make: RecallView$Options
};

function correctionClassname(correction) {
  switch (correction) {
    case "Correct" :
        return "correct";
    case "Missed" :
        return "missed";
    case "Incorrect" :
        return "incorrect";
    case "Blank" :
        return "blank";
    
  }
}

function RecallView$BackOptions(props) {
  var options = props.options;
  TiliaReact.useTilia();
  if (options.length === 0) {
    return JsxRuntime.jsx(JsxRuntime.Fragment, {});
  } else {
    return JsxRuntime.jsx("ul", {
                children: options.map(function (option) {
                      return JsxRuntime.jsxs("li", {
                                  children: [
                                    JsxRuntime.jsx("input", {
                                          defaultChecked: option.checked,
                                          type: "checkbox"
                                        }),
                                    JsxRuntime.jsx(make, {
                                          text: "\n\n" + option.content + "\n\n"
                                        })
                                  ],
                                  className: correctionClassname(option.correction)
                                }, option.id);
                    }),
                className: "options"
              });
  }
}

var BackOptions = {
  correctionClassname: correctionClassname,
  make: RecallView$BackOptions
};

function RecallView$Front(props) {
  var front = props.front;
  TiliaReact.useTilia();
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(make, {
                              text: front.content
                            }),
                        JsxRuntime.jsx(RecallView$Options, {
                              options: front.options
                            })
                      ],
                      className: "card-question"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("details", {
                            children: JsxRuntime.jsx("summary", {
                                  children: "Solution"
                                }),
                            open: false
                          }),
                      className: "card-anwser",
                      onClick: (function (param) {
                          front.turn();
                        })
                    })
              ],
              className: "card"
            });
}

var Front = {
  make: RecallView$Front
};

function RecallView$Evaluate(props) {
  var back = props.back;
  TiliaReact.useTilia();
  var hasErrors = back.options.some(function (option) {
        if (option.correction === "Missed") {
          return true;
        } else {
          return option.correction === "Incorrect";
        }
      });
  var evaluate = function (state) {
    back.evaluate(state);
    Browser.scrollTo("recall", "instant");
  };
  var tmp;
  if (hasErrors) {
    tmp = JsxRuntime.jsx(JsxRuntime.Fragment, {});
  } else {
    var match = back.prevState;
    var tmp$1;
    if (match !== undefined && typeof match === "object") {
      var i = match._0;
      tmp$1 = JsxRuntime.jsx(JsxRuntime.Fragment, {
            children: Caml_option.some(JsxRuntime.jsx("button", {
                      children: "Facile " + (i + 2 | 0).toString() + "x",
                      className: "eval easy-plus",
                      onClick: (function (param) {
                          evaluate({
                                kind: "easy",
                                _0: i + 1 | 0
                              });
                        })
                    }))
          });
    } else {
      tmp$1 = JsxRuntime.jsx(JsxRuntime.Fragment, {});
    }
    tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
          children: [
            JsxRuntime.jsx("button", {
                  children: "Bien",
                  className: "eval good",
                  onClick: (function (param) {
                      evaluate("good");
                    })
                }),
            JsxRuntime.jsx("button", {
                  children: "Facile",
                  className: "eval easy",
                  onClick: (function (param) {
                      evaluate({
                            kind: "easy",
                            _0: 0
                          });
                    })
                }),
            tmp$1
          ]
        });
  }
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                      children: "Encore",
                      className: "eval again",
                      onClick: (function (param) {
                          evaluate("again");
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "Difficile",
                      className: "eval hard",
                      onClick: (function (param) {
                          evaluate("hard");
                        })
                    }),
                tmp
              ],
              className: "card-evaluate"
            });
}

var Evaluate = {
  make: RecallView$Evaluate
};

function RecallView$Back(props) {
  var back = props.back;
  TiliaReact.useTilia();
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(make, {
                              text: back.content
                            }),
                        JsxRuntime.jsx(RecallView$BackOptions, {
                              options: back.options
                            })
                      ],
                      className: "card-question"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("details", {
                            children: [
                              JsxRuntime.jsx("summary", {
                                    children: "Solution",
                                    onClick: (function (param) {
                                        back.turn();
                                      })
                                  }),
                              JsxRuntime.jsx(RecallView$Evaluate, {
                                    back: back
                                  }),
                              JsxRuntime.jsx(make, {
                                    text: back.solution
                                  }),
                              JsxRuntime.jsx(RecallView$Evaluate, {
                                    back: back
                                  })
                            ],
                            open: true
                          }),
                      className: "card-answer"
                    })
              ],
              className: "card"
            });
}

var Back = {
  make: RecallView$Back
};

function RecallView$Done(props) {
  TiliaReact.useTilia();
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsxs("p", {
                          children: [
                            "Tout est terminé. Si vous voulez revoir encore, cliquez sur le bouton.",
                            JsxRuntime.jsx("button", {
                                  children: "Plus",
                                  className: "more",
                                  onClick: (function (param) {
                                      App.app.done();
                                    })
                                })
                          ]
                        }),
                    className: "card-question"
                  }),
              className: "card"
            });
}

var Done = {
  make: RecallView$Done
};

function RecallView(props) {
  var recall = props.recall;
  TiliaReact.useTilia();
  var front = recall.view;
  var tmp;
  tmp = typeof front !== "object" ? JsxRuntime.jsx(RecallView$Done, {}) : (
      front.TAG === "Front" ? JsxRuntime.jsx(RecallView$Front, {
              front: front._0
            }) : JsxRuntime.jsx(RecallView$Back, {
              back: front._0
            })
    );
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
              children: Caml_option.some(JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("a", {
                                id: "recall"
                              }),
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsx("span", {
                                        children: "session"
                                      }),
                                  JsxRuntime.jsx("span", {
                                        children: recall.stats.stackCount.toString(),
                                        className: "col-span-3 font-bold text-left"
                                      }),
                                  JsxRuntime.jsx("span", {
                                        children: "à réviser"
                                      }),
                                  JsxRuntime.jsx("span", {
                                        children: recall.stats.toRecall.toString(),
                                        className: "num"
                                      }),
                                  JsxRuntime.jsx("span", {
                                        children: "vues"
                                      }),
                                  JsxRuntime.jsx("span", {
                                        children: recall.stats.seen.toString(),
                                        className: "num"
                                      }),
                                  JsxRuntime.jsx("span", {
                                        children: "nouvelles"
                                      }),
                                  JsxRuntime.jsx("span", {
                                        children: recall.stats.new.toString(),
                                        className: "num"
                                      }),
                                  JsxRuntime.jsx("span", {
                                        children: "total"
                                      }),
                                  JsxRuntime.jsx("span", {
                                        children: recall.stats.total.toString(),
                                        className: "num"
                                      })
                                ],
                                className: "stats"
                              }),
                          tmp
                        ],
                        className: "card-wrapper"
                      }))
            });
}

var make$1 = RecallView;

export {
  Markdown ,
  Options ,
  BackOptions ,
  Front ,
  Evaluate ,
  Back ,
  Done ,
  make$1 as make,
}
/* make Not a pure module */
