// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as Stack from "../domain/api/entity/Stack.mjs";
import * as Utils from "../service/Utils.mjs";
import * as RecallView from "./RecallView.mjs";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function translateLevel(level) {
  if (level === "regular") {
    return "Parcours doux";
  } else {
    return "Parcours intensif";
  }
}

function translateType(stackType) {
  if (stackType === "cards") {
    return "Fiches de révision";
  } else {
    return "Quiz";
  }
}

function RecallTocView$ChapterProgress(props) {
  var chapter = props.chapter;
  TiliaReact.useTilia();
  var match = App.app.toc;
  var setActive = match.setActive;
  var prog = chapter.prog;
  if (typeof prog !== "object") {
    if (prog === "Loading") {
      return JsxRuntime.jsx("span", {
                  children: "Loading..."
                });
    } else {
      return JsxRuntime.jsx("input", {
                  checked: false,
                  type: "checkbox",
                  onChange: (function (param) {
                      setActive(chapter.info.id, true);
                    })
                });
    }
  }
  var prog$1 = prog._0;
  return JsxRuntime.jsx("input", {
              checked: prog$1.active,
              type: "checkbox",
              onChange: (function (param) {
                  setActive(chapter.info.id, !prog$1.active);
                })
            });
}

var ChapterProgress = {
  make: RecallTocView$ChapterProgress
};

function RecallTocView$ChapterItem(props) {
  var chapter = props.chapter;
  TiliaReact.useTilia();
  return JsxRuntime.jsx("li", {
              children: JsxRuntime.jsxs("a", {
                    children: [
                      JsxRuntime.jsx("span", {
                            children: JsxRuntime.jsx(RecallTocView$ChapterProgress, {
                                  chapter: chapter
                                }),
                            className: "toggle"
                          }),
                      JsxRuntime.jsx("span", {
                            children: Stack.stackTypeToEmoji(chapter.info.kind),
                            className: "emoji"
                          }),
                      " ",
                      chapter.info.chapter
                    ],
                    href: chapter.info.chapter
                  })
            }, chapter.info.id);
}

var ChapterItem = {
  make: RecallTocView$ChapterItem
};

function RecallTocView$CourseGroup(props) {
  var courseGroup = props.courseGroup;
  TiliaReact.useTilia();
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsx("h4", {
                      children: JsxRuntime.jsx("a", {
                            children: courseGroup.key,
                            href: "/" + courseGroup.key + "#" + Stack.levelToString(props.level)
                          })
                    }),
                JsxRuntime.jsx("ul", {
                      children: courseGroup.list.map(function (chapter) {
                            return JsxRuntime.jsx(RecallTocView$ChapterItem, {
                                        chapter: chapter
                                      }, chapter.info.id);
                          })
                    })
              ],
              className: "course"
            }, courseGroup.key);
}

var CourseGroup = {
  make: RecallTocView$CourseGroup
};

function RecallTocView$TypeGroup(props) {
  var level = props.level;
  var typeGroup = props.typeGroup;
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsx("h3", {
                      children: JsxRuntime.jsxs("a", {
                            children: [
                              JsxRuntime.jsx("span", {
                                    children: Stack.stackTypeToEmoji(typeGroup.key),
                                    className: "emoji"
                                  }),
                              " ",
                              translateType(typeGroup.key)
                            ],
                            id: Stack.stackTypeToString(typeGroup.key),
                            href: "/#" + Stack.stackTypeToString(typeGroup.key)
                          })
                    }),
                Utils.partition(typeGroup.list, (function (v) {
                          return v.info.course;
                        })).map(function (courseGroup) {
                      return JsxRuntime.jsx(RecallTocView$CourseGroup, {
                                  courseGroup: courseGroup,
                                  level: level
                                }, courseGroup.key);
                    })
              ],
              className: "type"
            }, Stack.stackTypeToString(typeGroup.key));
}

var TypeGroup = {
  make: RecallTocView$TypeGroup
};

function RecallTocView$LevelGroup(props) {
  var levelGroup = props.levelGroup;
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: translateLevel(levelGroup.key),
                      className: Stack.levelToString(levelGroup.key)
                    }),
                Utils.partition(levelGroup.list, (function (v) {
                          return v.info.kind;
                        })).map(function (typeGroup) {
                      return JsxRuntime.jsx(RecallTocView$TypeGroup, {
                                  typeGroup: typeGroup,
                                  level: levelGroup.key
                                }, Stack.stackTypeToString(typeGroup.key));
                    })
              ],
              className: "level",
              id: Stack.levelToString(levelGroup.key)
            }, Stack.levelToString(levelGroup.key));
}

var LevelGroup = {
  make: RecallTocView$LevelGroup
};

function RecallTocView(props) {
  TiliaReact.useTilia();
  var levelGroups = Utils.partition(App.app.toc.stacks, (function (v) {
          return v.info.level;
        }));
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(RecallView.make, {}),
                JsxRuntime.jsx("button", {
                      children: "Start",
                      className: "start",
                      onClick: (function (param) {
                          App.app.start();
                        })
                    }),
                JsxRuntime.jsx("nav", {
                      children: levelGroups.toSorted(function (a, b) {
                              var levelOrder = function (level) {
                                if (level === "regular") {
                                  return 0;
                                } else {
                                  return 1;
                                }
                              };
                              return levelOrder(a.key) - levelOrder(b.key);
                            }).map(function (levelGroup) {
                            return JsxRuntime.jsx(RecallTocView$LevelGroup, {
                                        levelGroup: levelGroup
                                      }, Stack.levelToString(levelGroup.key));
                          }),
                      "aria-label": "Table des matières",
                      className: "toc"
                    })
              ]
            });
}

var make = RecallTocView;

export {
  translateLevel ,
  translateType ,
  ChapterProgress ,
  ChapterItem ,
  CourseGroup ,
  TypeGroup ,
  LevelGroup ,
  make ,
}
/* App Not a pure module */
