// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as TiliaReact from "@tilia/react/src/TiliaReact.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function RecallView$Front(props) {
  return JsxRuntime.jsx("div", {
              children: props.front.content
            });
}

var Front = {
  make: RecallView$Front
};

function RecallView$Back(props) {
  return JsxRuntime.jsx("div", {
              children: props.back.content
            });
}

var Back = {
  make: RecallView$Back
};

function RecallView$RecallView(props) {
  TiliaReact.useTilia();
  var front = props.recall.view;
  if (front.TAG === "Front") {
    return JsxRuntime.jsx(RecallView$Front, {
                front: front._0
              });
  } else {
    return JsxRuntime.jsx(RecallView$Back, {
                back: front._0
              });
  }
}

var RecallView = {
  make: RecallView$RecallView
};

function RecallView$1(props) {
  TiliaReact.useTilia();
  var recall = App.app.recall;
  if (recall !== undefined) {
    return JsxRuntime.jsx(RecallView$RecallView, {
                recall: recall
              });
  } else {
    return JsxRuntime.jsx("div", {
                children: "No recall found"
              });
  }
}

var make = RecallView$1;

export {
  Front ,
  Back ,
  RecallView ,
  make ,
}
/* App Not a pure module */
